# Configuration for archiver.
# Comment out any section to disable that feature.

[archiver]

storage_backend="dropbox"

[dropbox]
token="DROPBOX_TOKEN_GOES_HERE"

[[flysight]]
name = "data"
mountpoint = "test-data/flysight"

[[mass_storage]]
name = "video"
mountpoint="test-data/mass_storage"
extensions=["mp4"]

[[flysight]]
name = "unmounted_fs"
mountpoint = "test-data/unmounted_fs"

[[mass_storage]]
name = "unmounted_ms"
mountpoint="test-data/unmounted_ms"
extensions=["mp4"]

[[flysight]]
name = "nonexistant_fs"
mountpoint="test-data/nonexistant_fs"
extensions=["ogv"]

[[mass_storage]]
name = "nonexistant_ms"
mountpoint="test-data/nonexistant_ms"
extensions=["ogv"]
